"use client";

import type { Language, LessonBlock } from "@/content/types";
import { SourceBadge } from "./SourceSystem";
import { CheckIcon, ChevronDownIcon } from "./icons";

function BlockShell({ block, language, children, className="" }: { block:LessonBlock; language:Language; children:React.ReactNode; className?:string }) {
  return <section id={block.key} data-block-key={block.key} data-block-type={block.type} className={`lesson-block ${className}`} aria-labelledby={`${block.key}-title`}><header className="block-heading"><div><span className="eyebrow">{language==="ar"?"المحطة":"Lesson moment"}</span><h2 id={`${block.key}-title`}>{block.title[language]}</h2></div><SourceBadge sourceKeys={block.sourceKeys}/></header>{children}</section>;
}
const paragraphs=(items:string[])=>items.map((item,index)=><p key={index}>{item}</p>);

export function HookBlock({block,language}:{block:LessonBlock;language:Language}){return <BlockShell block={block} language={language} className="hook-block"><div className="prose">{paragraphs(block.items[language])}</div></BlockShell>}

export function FactsStrip({block,language}:{block:LessonBlock;language:Language}){return <BlockShell block={block} language={language} className="facts-block"><div className="facts-grid">{block.items[language].map((item,index)=>{const parts=item.split(/:|：/);return <div className="fact-item" key={index}><span>{parts[0]}</span><strong>{parts.slice(1).join(":").trim()||item}</strong>{index===3&&<details><summary>{language==="ar"?"التوضيح المختصر":"Brief clarification"}</summary><p>{language==="ar"?"هذا هو قول أكثر العلماء، مع ورود أقوال أخرى في كتب التفسير.":"This is the majority classification; other positions are recorded in tafsir works."}</p></details>}</div>})}</div></BlockShell>}

export function KeyEvidenceBlock({block,language}:{block:LessonBlock;language:Language}){const items=block.items[language];return <BlockShell block={block} language={language} className="evidence-block"><div className="quote-pair"><blockquote>{items[0]}</blockquote><blockquote>{items[2]}</blockquote></div><div className="prose">{[items[1],...items.slice(3)].map((item,index)=><p key={index}>{item}</p>)}</div></BlockShell>}

export function NameCards({block,language}:{block:LessonBlock;language:Language}){const items=block.items[language];return <BlockShell block={block} language={language} className="names-block"><div className="name-grid">{items.slice(0,3).map((item,index)=>{const [name,...rest]=item.split(" — ");return <article className="name-card" key={index}><span>{language==="ar"?`الاسم ${index+1}`:`Name ${index+1}`}</span><h3>{name}</h3><p>{rest.join(" — ")}</p><SourceBadge sourceKeys={block.sourceKeys} compact/></article>})}</div><div className="prose compact">{paragraphs(items.slice(3))}</div></BlockShell>}

export function SevenOftRepeated({block,language}:{block:LessonBlock;language:Language}){const items=block.items[language];return <BlockShell block={block} language={language} className="scripture-block"><blockquote className="quran-quote">{items[0]}</blockquote><div className="prose">{paragraphs(items.slice(1,3))}</div><details className="clarification"><summary><span>{language==="ar"?"كيف تُعَدّ الآيات السبع؟":"How are the seven verses counted?"}</span><ChevronDownIcon/></summary><p>{items[3]}</p></details></BlockShell>}

export function HadithConversation({block,language}:{block:LessonBlock;language:Language}){const items=block.items[language];const stages=items.slice(3,6);return <BlockShell block={block} language={language} className="hadith-feature"><p className="hadith-lead">{items[0]}</p><blockquote>{items[1]}</blockquote><div className="hadith-stages">{stages.map((item,index)=><article key={index}><span>{index+1}</span><p>{item}</p></article>)}</div><details className="hadith-understand"><summary><span>{language==="ar"?"افهم هذا الحديث":"Understand this hadith"}</span><ChevronDownIcon/></summary><div className="prose">{paragraphs([items[2],...items.slice(6)])}</div></details></BlockShell>}

export function ThemeJourney({block,language}:{block:LessonBlock;language:Language}){const items=block.items[language];return <BlockShell block={block} language={language} className="theme-block"><div className="theme-journey">{items.map((item,index)=>{const numbered=/^[١٢٣٤٥٦1-6][\.،.]/.test(item);if(!numbered)return <p className="theme-intro" key={index}>{item}</p>;const match=item.match(/^([١٢٣٤٥٦1-6])[\.،.]\s*(.*)$/);const text=match?.[2]??item;const [title,...rest]=text.split(" — ");return <article key={index}><span>{match?.[1]}</span><div><h3>{title}</h3><p>{rest.join(" — ")}</p></div></article>})}</div></BlockShell>}

export function ReflectionPanel({block,language}:{block:LessonBlock;language:Language}){return <BlockShell block={block} language={language} className="reflection-block"><span className="reflection-label">{language==="ar"?"تأمل في صلاتك":"Notice this in prayer"}</span><div className="prose">{paragraphs(block.items[language])}</div></BlockShell>}

export function SummaryChecklist({block,language}:{block:LessonBlock;language:Language}){return <BlockShell block={block} language={language} className="summary-block"><ul>{block.items[language].map((item,index)=><li key={index}><CheckIcon/><span>{item.replace(/^[١٢٣٤٥1-5][\.،.]\s*/,"")}</span></li>)}</ul></BlockShell>}

export function LessonBlockRenderer({block,language}:{block:LessonBlock;language:Language}){switch(block.type){case"lesson_hook":return <HookBlock block={block} language={language}/>;case"surah_facts":return <FactsStrip block={block} language={language}/>;case"key_evidence":return <KeyEvidenceBlock block={block} language={language}/>;case"name_cards":return <NameCards block={block} language={language}/>;case"seven_oft_repeated":return <SevenOftRepeated block={block} language={language}/>;case"hadith_conversation":return <HadithConversation block={block} language={language}/>;case"theme_journey":return <ThemeJourney block={block} language={language}/>;case"reflection":return <ReflectionPanel block={block} language={language}/>;case"summary":return <SummaryChecklist block={block} language={language}/>;default:return null;}}
