"use client";

import type { Language, LessonBlock } from "@/content/types";
import { SourceBadge } from "./SourceSystem";
import { CheckIcon, ChevronDownIcon } from "./icons";

type BlockProps = { block:LessonBlock; language:Language; expandedDeepIds:string[]; onToggleDeep:(id:string,open:boolean)=>void };

function BlockShell({ block, language, children, className="", expandedDeepIds, onToggleDeep }: BlockProps & { children:React.ReactNode; className?:string }) {
  return <section id={block.key} data-block-key={block.key} data-block-type={block.type} className={`lesson-block ${className}`} aria-labelledby={`${block.key}-title`}><header className="block-heading"><div><span className="eyebrow">{language==="ar"?"الفكرة الأساسية":"Core idea"}</span><h2 id={`${block.key}-title`}>{block.title[language]}</h2></div><SourceBadge sourceKeys={block.sourceKeys} label={block.sourceSummary[language]}/></header>{children}{block.deepSections.length>0&&<div className="deep-section-list" data-testid="deep-sections">{block.deepSections.map(section=><details className="deep-section" key={section.key} open={expandedDeepIds.includes(section.key)} onToggle={event=>onToggleDeep(section.key,event.currentTarget.open)}><summary><span><small>{language==="ar"?"تعمّق أكثر":"Go deeper"}</small><strong>{section.title[language]}</strong></span><ChevronDownIcon/></summary><div className="deep-section-body"><div className="prose">{paragraphs(section.items[language])}</div><SourceBadge sourceKeys={section.sourceKeys} label={language==="ar"?"مصادر هذا التعمق":"Sources for this insight"}/></div></details>)}</div>}</section>;
}
const paragraphs=(items:string[])=>items.map((item,index)=><p key={index}>{item}</p>);

export function HookBlock(props:BlockProps){const{block,language}=props;return <BlockShell {...props} className="hook-block"><div className="prose">{paragraphs(block.items[language])}</div></BlockShell>}

export function FactsStrip(props:BlockProps){const{block,language}=props;return <BlockShell {...props} className="facts-block"><div className="facts-grid">{block.items[language].map((item,index)=>{const parts=item.split(/:|：/);return <div className="fact-item" key={index}><span>{parts[0]}</span><strong>{parts.slice(1).join(":").trim()||item}</strong>{index===3&&<details><summary>{language==="ar"?"التوضيح المختصر":"Brief clarification"}</summary><p>{language==="ar"?"هذا هو قول أكثر العلماء، مع ورود أقوال أخرى في كتب التفسير.":"This is the majority classification; other positions are recorded in tafsir works."}</p></details>}</div>})}</div></BlockShell>}

const QUOTE_CHARS=/[«»“”"]/;
/** True only when items[0] and items[2] actually look like quotations (this block's "quote-pair" layout assumes exactly that shape; plain factual prose must not be styled as a quotation). */
function looksLikeQuotePair(items:string[]){return items.length>=3&&QUOTE_CHARS.test(items[0])&&QUOTE_CHARS.test(items[2]);}
export function KeyEvidenceBlock(props:BlockProps){const{block,language}=props;const items=block.items[language];if(!looksLikeQuotePair(items))return <BlockShell {...props} className="evidence-block"><ul className="grouped-list">{items.map((item,index)=><li className="grouped-list-item" key={index}><p>{item}</p></li>)}</ul></BlockShell>;return <BlockShell {...props} className="evidence-block"><div className="quote-pair"><blockquote>{items[0]}</blockquote><blockquote>{items[2]}</blockquote></div><div className="prose">{[items[1],...items.slice(3)].map((item,index)=><p key={index}>{item}</p>)}</div></BlockShell>}

/** True only when the first 3 items are actually clean "Name — description" pairs (exactly one em-dash each); running prose that merely contains a parenthetical em-dash must not be split into a fabricated name/description pair. */
function looksLikeNameCardSet(items:string[]){return items.length>3&&items.slice(0,3).every((item)=>(item.match(/ — /g)??[]).length===1);}
export function NameCards(props:BlockProps){const{block,language}=props;const items=block.items[language];if(!looksLikeNameCardSet(items))return <BlockShell {...props} className="names-block"><ul className="grouped-list">{items.map((item,index)=><li className="grouped-list-item" key={index}><p>{item}</p></li>)}</ul></BlockShell>;return <BlockShell {...props} className="names-block"><div className="name-grid">{items.slice(0,3).map((item,index)=>{const [name,...rest]=item.split(" — ");return <article className="name-card" key={index}><span>{language==="ar"?`الاسم ${index+1}`:`Name ${index+1}`}</span><h3>{name}</h3><p>{rest.join(" — ")}</p></article>})}</div><div className="prose compact">{paragraphs(items.slice(3))}</div></BlockShell>}

export function SevenOftRepeated(props:BlockProps){const{block,language}=props;const items=block.items[language];return <BlockShell {...props} className="scripture-block"><blockquote className="quran-quote">{items[0]}</blockquote><div className="prose">{paragraphs(items.slice(1,3))}</div><details className="clarification"><summary><span>{language==="ar"?"كيف تُعَدّ الآيات السبع؟":"How are the seven verses counted?"}</span><ChevronDownIcon/></summary><p>{items[3]}</p></details></BlockShell>}

export function HadithConversation(props:BlockProps){const{block,language}=props;const items=block.items[language];const stages=items.slice(3,6);return <BlockShell {...props} className="hadith-feature"><p className="hadith-lead">{items[0]}</p><blockquote>{items[1]}</blockquote><div className="hadith-stages">{stages.map((item,index)=><article key={index}><span>{index+1}</span><p>{item}</p></article>)}</div><details className="hadith-understand"><summary><span>{language==="ar"?"افهم هذا الحديث":"Understand this hadith"}</span><ChevronDownIcon/></summary><div className="prose">{paragraphs([items[2],...items.slice(6)])}</div></details></BlockShell>}

export function ThemeJourney(props:BlockProps){const{block,language}=props;const items=block.items[language];return <BlockShell {...props} className="theme-block"><div className="theme-journey">{items.map((item,index)=>{const numbered=/^[١٢٣٤٥٦1-6][\.،.]/.test(item);if(!numbered)return <p className="theme-intro" key={index}>{item}</p>;const match=item.match(/^([١٢٣٤٥٦1-6])[\.،.]\s*(.*)$/);const text=match?.[2]??item;const [title,...rest]=text.split(" — ");return <article key={index}><span>{match?.[1]}</span><div><h3>{title}</h3><p>{rest.join(" — ")}</p></div></article>})}</div></BlockShell>}

export function ReflectionPanel(props:BlockProps){const{block,language}=props;return <BlockShell {...props} className="reflection-block"><span className="reflection-label">{language==="ar"?"تأمل في صلاتك":"Notice this in prayer"}</span><div className="prose">{paragraphs(block.items[language])}</div></BlockShell>}

export function SummaryChecklist(props:BlockProps){const{block,language}=props;return <BlockShell {...props} className="summary-block"><ul>{block.items[language].map((item,index)=><li key={index}><CheckIcon/><span>{item.replace(/^[١٢٣٤٥1-5][\.،.]\s*/,"")}</span></li>)}</ul></BlockShell>}

export function LessonBlockRenderer(props:BlockProps){switch(props.block.type){case"lesson_hook":return <HookBlock {...props}/>;case"surah_facts":return <FactsStrip {...props}/>;case"key_evidence":return <KeyEvidenceBlock {...props}/>;case"name_cards":return <NameCards {...props}/>;case"seven_oft_repeated":return <SevenOftRepeated {...props}/>;case"hadith_conversation":return <HadithConversation {...props}/>;case"theme_journey":return <ThemeJourney {...props}/>;case"reflection":return <ReflectionPanel {...props}/>;case"summary":return <SummaryChecklist {...props}/>;case"representative_event":return <HookBlock {...props}/>;case"context_and_consequence":return <HookBlock {...props}/>;case"event_consequence_meaning":return <HookBlock {...props}/>;default:return null;}}
